module Intrigue
  module Ident
  module RedisCheck
  class RedisCheck < Intrigue::Ident::RedisCheck::Base
  
    def generate_checks 
      [
        {
          :type => "fingerprint",
          :category => "application",
          :tags => ["RedisServer"],
          :vendor => "Redislabs",
          :product => "Redis",
          :references => [],
          :version => nil,
          :match_type => :content_redis_version,
          :match_content => /[\d\.]+/i,
          :dynamic_version => lambda { |x| _info_key_capture(x, "redis_version")},
          :match_details => "redis version",
          :inference => true
        }
      ]
    end
  end
  end
  end
  end
  
=begin

{"redis_version"=>"5.0.10",
 "redis_git_sha1"=>"00000000",
 "redis_git_dirty"=>"0",
 "redis_build_id"=>"74a46299703931d5",
 "redis_mode"=>"standalone",
 "os"=>"Linux 3.10.0-957.21.3.el7.x86_64 x86_64",
 "arch_bits"=>"64",
 "multiplexing_api"=>"epoll",
 "atomicvar_api"=>"atomic-builtin",
 "gcc_version"=>"4.8.5",
 "process_id"=>"17758",
 "run_id"=>"f2f00c56af2265614bc72bcca0f5479f6d81d4ba",
 "tcp_port"=>"6379",
 "uptime_in_seconds"=>"105316",
 "uptime_in_days"=>"1",
 "hz"=>"10",
 "configured_hz"=>"10",
 "lru_clock"=>"13600281",
 "executable"=>"/usr/local/redis/bin/redis-server",
 "config_file"=>"/usr/local/redis/etc/redis.conf",
 "connected_clients"=>"1",
 "client_recent_max_input_buffer"=>"2",
 "client_recent_max_output_buffer"=>"0",
 "blocked_clients"=>"0",
 "used_memory"=>"855168",
 "used_memory_human"=>"835.12K",
 "used_memory_rss"=>"8630272",
 "used_memory_rss_human"=>"8.23M",
 "used_memory_peak"=>"5448992",
 "used_memory_peak_human"=>"5.20M",
 "used_memory_peak_perc"=>"15.69%",
 "used_memory_overhead"=>"841478",
 "used_memory_startup"=>"791400",
 "used_memory_dataset"=>"13690",
 "used_memory_dataset_perc"=>"21.47%",
 "allocator_allocated"=>"1074056",
 "allocator_active"=>"1462272",
 "allocator_resident"=>"8794112",
 "total_system_memory"=>"7918817280",
 "total_system_memory_human"=>"7.37G",
 "used_memory_lua"=>"37888",
 "used_memory_lua_human"=>"37.00K",
 "used_memory_scripts"=>"0",
 "used_memory_scripts_human"=>"0B",
 "number_of_cached_scripts"=>"0",
 "maxmemory"=>"0",
 "maxmemory_human"=>"0B",
 "maxmemory_policy"=>"noeviction",
 "allocator_frag_ratio"=>"1.36",
 "allocator_frag_bytes"=>"388216",
 "allocator_rss_ratio"=>"6.01",
 "allocator_rss_bytes"=>"7331840",
 "rss_overhead_ratio"=>"0.98",
 "rss_overhead_bytes"=>"-163840",
 "mem_fragmentation_ratio"=>"10.90",
 "mem_fragmentation_bytes"=>"7838240",
 "mem_not_counted_for_evict"=>"0",
 "mem_replication_backlog"=>"0",
 "mem_clients_slaves"=>"0",
 "mem_clients_normal"=>"49694",
 "mem_aof_buffer"=>"0",
 "mem_allocator"=>"jemalloc-5.1.0",
 "active_defrag_running"=>"0",
 "lazyfree_pending_objects"=>"0",
 "loading"=>"0",
 "rdb_changes_since_last_save"=>"76",
 "rdb_bgsave_in_progress"=>"0",
 "rdb_last_save_time"=>"1607414409",
 "rdb_last_bgsave_status"=>"err",
 "rdb_last_bgsave_time_sec"=>"0",
 "rdb_current_bgsave_time_sec"=>"-1",
 "rdb_last_cow_size"=>"331776",
 "aof_enabled"=>"0",
 "aof_rewrite_in_progress"=>"0",
 "aof_rewrite_scheduled"=>"0",
 "aof_last_rewrite_time_sec"=>"-1",
 "aof_current_rewrite_time_sec"=>"-1",
 "aof_last_bgrewrite_status"=>"ok",
 "aof_last_write_status"=>"ok",
 "aof_last_cow_size"=>"0",
 "total_connections_received"=>"197",
 "total_commands_processed"=>"2393",
 "instantaneous_ops_per_sec"=>"0",
 "total_net_input_bytes"=>"198861",
 "total_net_output_bytes"=>"1594294",
 "instantaneous_input_kbps"=>"0.00",
 "instantaneous_output_kbps"=>"0.00",
 "rejected_connections"=>"0",
 "sync_full"=>"0",
 "sync_partial_ok"=>"0",
 "sync_partial_err"=>"0",
 "expired_keys"=>"2",
 "expired_stale_perc"=>"0.00",
 "expired_time_cap_reached_count"=>"0",
 "evicted_keys"=>"0",
 "keyspace_hits"=>"46",
 "keyspace_misses"=>"18",
 "pubsub_channels"=>"0",
 "pubsub_patterns"=>"0",
 "latest_fork_usec"=>"358",
 "migrate_cached_sockets"=>"0",
 "slave_expires_tracked_keys"=>"0",
 "active_defrag_hits"=>"0",
 "active_defrag_misses"=>"0",
 "active_defrag_key_hits"=>"0",
 "active_defrag_key_misses"=>"0",
 "role"=>"master",
 "connected_slaves"=>"0",
 "master_replid"=>"29fe6291d6745b8ea8fa6743965f285f72d1a2d8",
 "master_replid2"=>"b4dc8d675667d1a8a91b3bd6e0141b2ec3c11282",
 "master_repl_offset"=>"0",
 "second_repl_offset"=>"1",
 "repl_backlog_active"=>"0",
 "repl_backlog_size"=>"1048576",
 "repl_backlog_first_byte_offset"=>"0",
 "repl_backlog_histlen"=>"0",
 "used_cpu_sys"=>"37.470124",
 "used_cpu_user"=>"58.422439",
 "used_cpu_sys_children"=>"2.379693",
 "used_cpu_user_children"=>"3.480385",
 "cluster_enabled"=>"0",
 "db0"=>"keys=8,expires=0,avg_ttl=0"}


=end