module Intrigue
module Ident
module Check
class WordpressJohnGodley < Intrigue::Ident::Check::Base

  def generate_checks(url)
    [
      {
        :type => "fingerprint",
        :category => "application",
        :tags => ["Wordpress Plugin"],
        :vendor =>"John Godley",
        :product =>"Redirection",
        :match_details =>"generated by string (body)",
        :references => [],
        :match_type => :content_body,
        :match_content =>  /redirection\\\/v1/i,
        :version => nil,
        :paths => ["#{url}/wp-json"],
        :require_product => "Wordpress",
        :inference => false
      }
    ]
  end

end
end
end
end
