source 'https://rubygems.org'
ruby '2.6.5'

gem 'pry'
gem 'socketry'
gem 'recog-intrigue',         :git => 'https://github.com/intrigueio/recog.git'
gem 'slop'
gem 'snmp'
gem 'dnsruby'
gem 'json'
gem 'rspec-core'
gem 'rspec-expectations'