module Intrigue
module Ident
module Check
class Axinom < Intrigue::Ident::Check::Base

  def generate_checks(url)
    [
      {
        type: "fingerprint",
        category: "service",
        tags: ["CMS"],
        vendor: "axinom GmbH",
        product: "AxCMS",
        references: ["http://help.axcms.net/"],
        version: nil,
        match_type: :content_body,
        match_content: /Generated by AxCMS.net/i,
        dynamic_version: lambda { |x|  _first_body_capture(x, /Generated by AxCMS.net (\d+)/i)},
        description: "comment match",
        hide: false,
        paths: [ { path: "#{url}", follow_redirects: true } ],
        inference: true
      }
    ]
  end

end
end
end
end
