module Intrigue
  module Ident
    module Check
      module Private
        class Cecil < Intrigue::Ident::Check::Base
          def generate_checks(url)
            [
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Development"],
                :vendor => "Cecil",
                :product => "Cecil",
                :website => "http://Cecil.org/",
                :match_details => "Cecil - generator page reference",
                :version => nil,
                :match_type => :content_body,
                :match_content => /<meta name="generator" content="Cecil/i,
                :dynamic_version => lambda { |x|
                  _first_body_capture(x, /<meta name="generator" content="Cecil (\d+(\.\d+)*)/i)
                },
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Development"],
                :vendor => "Cecil",
                :product => "Cecil",
                :website => "http://Cecil.org/",
                :match_details => "Cecil - generated by page reference",
                :version => nil,
                :match_type => :content_body,
                :match_content => /Generated by <a href="https:\/\/cecil\.app\/#(\d+(\.\d+)*)" class="text-reset" target="_blank" rel="noopener">Cecil /i,
                :dynamic_version => lambda { |x|
                  _first_body_capture(x, /Generated by <a href="https:\/\/cecil\.app\/#(\d+(\.\d+)*)" class="text-reset" target="_blank" rel="noopener">Cecil/i)
                },
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
            ]
          end
        end
      end
    end
  end
end
