module Intrigue
  module Ident
    module Check
      module Private
        class Cgit < Intrigue::Ident::Check::Base
          def generate_checks(url)
            [
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Development"],
                :vendor => "Cgit Project",
                :product => "Cgit",
                :website => "http://git.zx2c4.com/cgit",
                :match_details => "Cgit - generator page reference",
                :version => nil,
                :match_type => :content_body,
                :match_content => /<meta name="generator" content="cgit/i,
                :dynamic_version => lambda { |x|
                  _first_body_capture(x, /<meta name="generator" content="cgit v(\d+(\.\d+)*)/i)
                },
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Development"],
                :vendor => "Cgit Project",
                :product => "Cgit",
                :website => "http://git.zx2c4.com/cgit",
                :match_details => "Cgit - generated by reference",
                :version => nil,
                :match_type => :content_body,
                :match_content => /generated by\s*<a href="https:\/\/git.zx2c4.com\/cgit\/about\/">cgit/i,
                :dynamic_version => lambda { |x|
                  _first_body_capture(x, /generated by\s*<a href="https:\/\/git.zx2c4.com\/cgit\/about\/">cgit v(\d+(\.\d+)*)/i)
                },
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
            ]
          end
        end
      end
    end
  end
end
