module Intrigue
module Ident
module Check
class Citrix < Intrigue::Ident::Check::Base

  def generate_checks(url)
    [
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "Access Gateway",
        :match_details => "login page",
        :version => nil,
        :match_type => :content_title,
        :website => "https://www.citrix.com/downloads/citrix-gateway/access-gateway.html",
        :references => ["https://www.citrix.com/content/dam/citrix/en_us/documents/downloads/netscaler-access-gateway/Citrix_Access_Gateway_Spec_Sheet.pdf"],
        :match_content => /^Citrix Access Gateway$/i,
        :hide => false,
        :require_product => "NetScaler Gateway",
        :paths => ["#{url}/vpn/tmindex.html"],
        :inference => false,
        :issues => ["exposed_citrix_adc_management_interface"]
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway (Management Interface)",
        :match_details => "adc management interface",
        :version => nil,
        :match_type => :content_title,
        :match_content => /^Application Delivery Management$/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false,
        :issues => ["exposed_citrix_adc_management_interface"]
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "title",
        :version => nil,
        :match_type => :content_title,
        :match_content => /Citrix Gateway/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "logonpoint",
        :version => nil,
        :match_type => :content_body,
        :match_content => /_ctxstxt_CitrixCopyright/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "title",
        :version => nil,
        :match_type => :content_title,
        :match_content => /NetScaler Gateway/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "NSC_TMAC cookie",
        :version => nil,
        :match_type => :content_cookies,
        :match_content => /NSC_TMAC=/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "NSC_TEMP cookie",
        :version => nil,
        :match_type => :content_cookies,
        :match_content => /NSC_TEMP=/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "NSC_.*_NGB cookie",
        :version => nil,
        :match_type => :content_cookies,
        :match_content => /NSC_[\w]+_NGB=/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "NSC_PERS cookie",
        :version => nil,
        :match_type => :content_cookies,
        :match_content => /NSC_PERS=/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "(often) customized logon page - netscaler gateway",
        :version => nil,
        :match_type => :content_body,
        :match_content => /CTXMSAM_LogonFont/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "misspelled content-length header",
        :references => ["https://support.citrix.com/article/CTX211605"],
        :version => nil,
        :match_type => :content_headers,
        :match_content => /^cteonnt-length:.*$/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking","COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "cookie",
        :references => ["https://support.citrix.com/article/CTX131488"],
        :version => nil,
        :match_type => :content_cookies,
        :match_content => /citrix_ns_id=/i,
        :hide => false,
        :paths => ["#{url}"],
        :verify => ["dW5kZXJhcm1vdXIjSW50cmlndWU6OkVudGl0eTo6VXJpI2h0dHA6Ly8yMDQuMjkuMTk2LjEwMjo4MA=="],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking", "COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "redirect",
        :references => ["https://support.citrix.com/article/CTX131488"],
        :match_type => :content_headers,
        :match_content => /^location: \/vpn\/index\.html$/i ,
        :hide => false,
        :paths => ["#{url}/doesntexist-123"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "operating_system",
        :tags => ["Networking", "COTS", "VPN"],
        :vendor => "Citrix",
        :product => "NetScaler Gateway",
        :match_details => "cookie",
        :references => ["https://www.citrix.com/content/dam/citrix/en_us/documents/products-solutions/citrix-xenmobile-technology-overview.pdf"],
        :match_type => :content_cookies,
        :match_content => /NSC_TASS=\/doesntexist-123\/vpn\/index\.html/i ,
        :hide => false,
        :paths => ["#{url}/doesntexist-123"],
        :inference => false
      },  
      {
        :type => "fingerprint",
        :category => "application",
        :tags => ["Networking","COTS", "Hypervisor"],
        :vendor => "Citrix",
        :product => "XenMobile",
        :website => "https://www.citrix.com/products/citrix-endpoint-management/",
        :match_details => "redirect",
        :references => [],
        :version => nil,
        :match_type => :content_headers,
        :match_content => /^location: \/zdm\/login_xdm_uc.jsp$/i,
        :hide => false,
        :paths => ["#{url}"],
        :inference => true
      },
      {
        :type => "fingerprint",
        :category => "application",
        :tags => ["Networking","COTS", "Hypervisor"],
        :vendor => "Citrix",
        :product => "XenServer",
        :match_details => "page title",
        :references => [],
        :version => nil,
        :dynamic_version => lambda { |x| 
          _first_body_capture(x,/<title>XenServer (.*?)<\/title>/) 
        },
        :match_type => :content_body,
        :match_content => /<title>XenServer/,
        :hide => false,
        :paths => ["#{url}"],
        :inference => true
      },
      {
        :type => "fingerprint",
        :category => "application",
        :vendor => "Citrix",
        :tags => ["Networking","COTS", "Hypervisor"],
        :product => "XenServer",
        :match_details => "page title",
        :references => [],
        :version => nil,
        :dynamic_version => lambda { |x|
          _first_body_capture(x,/<title>Welcome to Citrix XenServer (.*?)<\/title>/)
        },
        :match_type => :content_body,
        :match_content => /<title>Welcome to Citrix XenServer/,
        :hide => false,
        :paths => ["#{url}"],
        :inference => true
      }
    ]
  end

end
end
end
end
