module Intrigue
  module Ident
    module Check
      module Private
        class CleanTalk < Intrigue::Ident::Check::Base
          def generate_checks(url)
            [
              {
                :type => "fingerprint",
                :category => "service",
                :tags => ["Cloud", "Security"],
                :vendor => "CleanTalk",
                :product => "CleanTalk",
                :website => "https://cleantalk.org/",
                :match_details => "CleanTalk - apbct_cookies_test cookie",
                :version => nil,
                :match_type => :content_cookies,
                :match_content => /apbct_cookies_test=/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
                :test_target => ["https://www.smiaware.com:443"],
              },
              {
                :type => "fingerprint",
                :category => "service",
                :tags => ["Cloud", "Security"],
                :vendor => "CleanTalk",
                :product => "CleanTalk",
                :website => "https://cleantalk.org/",
                :match_details => "CleanTalk - apbct_page_hits cookie",
                :version => nil,
                :match_type => :content_cookies,
                :match_content => /apbct_page_hits=/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
                :test_target => ["https://www.smiaware.com:443"],
              },
              {
                :type => "fingerprint",
                :category => "service",
                :tags => ["Cloud", "Security"],
                :vendor => "CleanTalk",
                :product => "CleanTalk",
                :website => "https://cleantalk.org/",
                :match_details => "CleanTalk - apbct_prev_referer cookie",
                :version => nil,
                :match_type => :content_cookies,
                :match_content => /apbct_prev_referer=/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
                :test_target => ["https://www.smiaware.com:443"],
              },
              {
                :type => "fingerprint",
                :category => "service",
                :tags => ["Cloud", "Security"],
                :vendor => "CleanTalk",
                :product => "CleanTalk",
                :website => "https://cleantalk.org/",
                :match_details => "CleanTalk - apbct_site_landing_ts cookie",
                :version => nil,
                :match_type => :content_cookies,
                :match_content => /apbct_site_landing_ts=/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
                :test_target => ["https://www.smiaware.com:443"],
              },
              {
                :type => "fingerprint",
                :category => "service",
                :tags => ["Cloud", "Security"],
                :vendor => "CleanTalk",
                :product => "CleanTalk",
                :website => "https://cleantalk.org/",
                :match_details => "CleanTalk - apbct_timestamp cookie",
                :version => nil,
                :match_type => :content_cookies,
                :match_content => /apbct_timestamp=/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
                :test_target => ["https://www.smiaware.com:443"],
              },
              {
                :type => "fingerprint",
                :category => "service",
                :tags => ["Cloud", "Security"],
                :vendor => "CleanTalk",
                :product => "CleanTalk",
                :website => "https://cleantalk.org/",
                :match_details => "CleanTalk - apbct_visible_fields cookie",
                :version => nil,
                :match_type => :content_cookies,
                :match_content => /apbct_visible_fields=/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
                :test_target => ["https://www.smiaware.com:443"],
              },
              {
                :type => "fingerprint",
                :category => "service",
                :tags => ["Cloud", "Security"],
                :vendor => "CleanTalk",
                :product => "CleanTalk",
                :website => "https://cleantalk.org/",
                :match_details => "CleanTalk - apbct_visible_fields_count cookie",
                :version => nil,
                :match_type => :content_cookies,
                :match_content => /apbct_visible_fields_count=/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
                :test_target => ["https://www.smiaware.com:443"],
              },
            ]
          end
        end
      end
    end
  end
end
