module Intrigue
module Ident
module Check
class Hubspot < Intrigue::Ident::Check::Base

  def generate_checks(url)
    [
      {
        :type => "fingerprint",
        :category => "service",
        :tags => ["Marketing", "Javascript"],
        :vendor => "Hubspot",
        :product =>"Analytics",
        :match_details =>"unique string",
        :version => nil,
        :match_type => :content_body,
        :match_content =>  /<!-- End of HubSpot Analytics Code -->/,
        :hide => false,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "service",
        :tags => ["Marketing", "Javascript"],
        :vendor => "Hubspot",
        :product =>"Template Builder",
        :references => [
          "https://www.betterhacker.com/2018/12/rce-in-hubspot-with-el-injection-in-hubl.html"
        ],
        :match_details =>"unique string",
        :version => nil,
        :match_type => :content_body,
        :dynamic_version => lambda {|x|
          _first_body_capture(x,/<!-- Generated by the HubSpot Template Builder - template version ([\d\.]*)  \ -->/i,)
        },
        :match_content =>  /<!-- Generated by the HubSpot Template Builder - template version [\d\.]*\ -->/,
        :hide => true,
        :paths => ["#{url}"],
        :inference => false
      },
      {
        :type => "fingerprint",
        :category => "service",
        :tags => ["Marketing"],
        :vendor => "Hubspot",
        :product =>"Hubspot",
        :match_details =>"generator string",
        :version => nil,
        :match_type => :content_generator,
        :match_content => /HubSpot/,
        :hide => true,
        :paths => ["#{url}"],
        :inference => false
      }
    ]
  end

end
end
end
end
