module Intrigue
  module Ident
    module Check
      module Private
        class Shopware < Intrigue::Ident::Check::Base
          def generate_checks(url)
            [
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["E-commerce"],
                :vendor => "Shopware",
                :product => "Shopware",
                :website => "https://www.shopware.com/",
                :match_details => "Shopware - application-name tag page reference",
                :version => nil,
                :match_type => :content_body,
                :match_content => /<meta name="application-name" content="Shopware"/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["E-commerce"],
                :vendor => "Shopware",
                :product => "Shopware",
                :website => "https://www.shopware.com/",
                :match_details => "Shopware - shopware.min.js page reference",
                :version => nil,
                :match_type => :content_body,
                :match_content => /<script type="text\/javascript" src=".*\/javascript\/jquery\.shopware\.min\.js.*"><\/script>/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["E-commerce"],
                :vendor => "Shopware",
                :product => "Shopware",
                :website => "https://www.shopware.com/",
                :match_details => "Shopware - shopware.js page reference",
                :version => nil,
                :match_type => :content_body,
                :match_content => /<script type="text\/javascript".* src=".*\/shopsystem\/shopware_\d+.js.*"><\/script>/i,
                :dynamic_version => lambda { |x|
                  _first_body_capture(x, /<script type="text\/javascript".* src=".*\/shopsystem\/shopware_(\d+).js.*"><\/script>/i)
                },
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["E-commerce"],
                :vendor => "Shopware",
                :product => "Shopware",
                :website => "https://www.shopware.com/",
                :match_details => "Shopware - sw-context-token header",
                :version => 6,
                :match_type => :content_headers,
                :match_content => /^sw-context-token/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["E-commerce"],
                :vendor => "Shopware",
                :product => "Shopware",
                :website => "https://www.shopware.com/",
                :match_details => "Shopware - sw-invalidation-states header",
                :version => 6,
                :match_type => :content_headers,
                :match_content => /^sw-invalidation-states/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["E-commerce"],
                :vendor => "Shopware",
                :product => "Shopware",
                :website => "https://www.shopware.com/",
                :match_details => "Shopware - sw-language-id header",
                :version => 6,
                :match_type => :content_headers,
                :match_content => /^sw-language-id/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["E-commerce"],
                :vendor => "Shopware",
                :product => "Shopware",
                :website => "https://www.shopware.com/",
                :match_details => "Shopware - sw-version-id header",
                :version => 6,
                :match_type => :content_headers,
                :match_content => /^sw-version-id/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["E-commerce"],
                :vendor => "Shopware",
                :product => "Shopware",
                :website => "https://www.shopware.com/",
                :match_details => "Shopware - sw-states cookie",
                :version => 6,
                :match_type => :content_cookies,
                :match_content => /sw-states=/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["E-commerce"],
                :vendor => "Shopware",
                :product => "Shopware",
                :website => "https://www.shopware.com/",
                :match_details => "Shopware - sw-cache-hash cookie",
                :version => 6,
                :match_type => :content_cookies,
                :match_content => /sw-cache-hash=/i,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
            ]
          end
        end
      end
    end
  end
end
