module Intrigue
  module Ident
    module Check
      module Private
        class Sympa < Intrigue::Ident::Check::Base
          def generate_checks(url)
            [
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Email", "Mail Server"],
                :vendor => "Sympa",
                :product => "Sympa",
                :website => "https://www.sympa.org/",
                :match_details => "Sympa Sympa - sympa_session Cookie Match",
                :version => nil,
                :match_type => :content_cookies,
                :match_content => /sympa_session=/,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Mail Server"],
                :vendor => "Sympa",
                :product => "Sympa",
                :website => "http://www.sympa.org/",
                :match_details => "Sympa - generator page reference",
                :version => nil,
                :match_type => :content_body,
                :match_content => /<meta name="generator" content="Sympa/i,
                :dynamic_version => lambda { |x|
                  _first_body_capture(x, /<meta name="generator" content="Sympa (\d+(\.\d+)*)/i)
                },
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Mail Server"],
                :vendor => "Sympa",
                :product => "Sympa",
                :website => "http://www.sympa.org/",
                :match_details => "Sympa - generated by page reference",
                :version => nil,
                :match_type => :content_body,
                :match_content => /<a href="http:\/\/www.sympa.org"> Powered by Sympa/i,
                :dynamic_version => lambda { |x|
                  _first_body_capture(x, /<a href="http:\/\/www.sympa.org"> Powered by Sympa (\d+(\.\d+)*)/i)
                },
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Mail Server"],
                :vendor => "Sympa",
                :product => "Sympa",
                :website => "http://www.sympa.org/",
                :match_details => "Sympa - sympa_session cookie",
                :version => nil,
                :match_type => :content_cookies,
                :match_content => /sympa_session=/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
            ]
          end
        end
      end
    end
  end
end
