module Intrigue
  module Ident
    module Check
      module Private
        class MattCheney < Intrigue::Ident::Check::Base
          def generate_checks(url)
            [
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Drupal Plugin"],
                :vendor => "Matt Cheney",
                :product => "Panopoly Images",
                :website => "https://www.drupal.org/project/panopoly_images",
                :match_details => "Matt Cheney Panopoly Images - panopoly-images.js Script Page Reference",
                :version => nil,
                :match_type => :content_body,
                :match_content => /(jquery\.extend\(drupal\.settings.*\\\/panopoly\\\/panopoly_images\\\/|<script.*src=".*\/panopoly\/panopoly_images\/)panopoly-images.js/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Drupal Plugin"],
                :vendor => "Matt Cheney",
                :product => "Panopoly Widgets",
                :website => "https://www.drupal.org/project/panopoly_widgets",
                :match_details => "Matt Cheney Panopoly Widgets - panopoly-widgets.css Link Page Reference",
                :version => nil,
                :match_type => :content_body,
                :require_product => "Drupal",
                :match_content => /(jquery\.extend\(drupal\.settings.*\\\/panopoly\\\/panopoly_widgets\\\/|<link.*href=".*\/panopoly\/panopoly_widgets\/)panopoly-widgets.css/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Drupal Plugin"],
                :vendor => "Matt Cheney",
                :product => "Panopoly Widgets",
                :website => "https://www.drupal.org/project/panopoly_widgets",
                :match_details => "Matt Cheney Panopoly Widgets - panopoly-widgets.js Script Page Reference",
                :version => nil,
                :match_type => :content_body,
                :require_product => "Drupal", #
                :match_content => /(jquery\.extend\(drupal\.settings.*\\\/panopoly\\\/panopoly_widgets\\\/|<script.*src=".*\/panopoly\/panopoly_widgets\/)panopoly-widgets.js/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Drupal Plugin"],
                :vendor => "Matt Cheney",
                :product => "Panopoly Widgets",
                :website => "https://www.drupal.org/project/panopoly_widgets",
                :match_details => "Matt Cheney Panopoly Widgets - panopoly-widgets-spotlight.js Script Page Reference",
                :version => nil,
                :match_type => :content_body,
                :require_product => "Drupal",
                :match_content => /(jquery\.extend\(drupal\.settings.*\\\/panopoly\\\/panopoly_widgets\\\/|<script.*src=".*\/panopoly\/panopoly_widgets\/)panopoly-widgets-spotlight.js/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Drupal Plugin"],
                :vendor => "Matt Cheney",
                :product => "Panopoly WYSIWYG",
                :website => "https://www.drupal.org/project/panopoly_wysiwyg",
                :match_details => "Matt Cheney Panopoly WYSIWYG - panopoly-wysiwyg.css Link Page Reference",
                :version => nil,
                :match_type => :content_body,
                :require_product => "Drupal",
                :match_content => /(jquery\.extend\(drupal\.settings.*\\\/panopoly\\\/panopoly_wysiwyg\\\/|<link.*href=".*\/panopoly\/panopoly_wysiwyg\/)panopoly-wysiwyg.css/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Drupal Plugin"],
                :vendor => "Panopoly Magic Project",
                :product => "Panopoly Magic",
                :website => "https://www.drupal.org/project/panopoly_magic",
                :match_details => "Matt Cheney Panopoly Magic - panopoly-magic.css Link Page Reference",
                :version => nil,
                :match_type => :content_body,
                :require_product => "Drupal",
                :match_content => /(jquery\.extend\(drupal\.settings.*\\\/panopoly\\\/panopoly_magic\\\/css\\\/|<link.*href=".*\/panopoly\/panopoly_magic\/css\/)panopoly-magic.css/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Drupal Plugin"],
                :vendor => "Panopoly Magic Project",
                :product => "Panopoly Magic",
                :website => "https://www.drupal.org/project/panopoly_magic",
                :match_details => "Matt Cheney Panopoly Magic - panopoly-magic.js Script Page Reference",
                :version => nil,
                :match_type => :content_body,
                :require_product => "Drupal",
                :match_content => /(jquery\.extend\(drupal\.settings.*\\\/panopoly\\\/panopoly_magic\\\/|<script.*src=".*\/panopoly\/panopoly_magic\/)panopoly-magic.js/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => true,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Drupal Plugin"],
                :vendor => "Matt Cheney",
                :product => "Panopoly Admin",
                :website => "https://www.drupal.org/project/panopoly_admin",
                :match_details => "Matt Cheney Panopoly Admin - panopoly-admin-navbar.css Link Page Reference",
                :version => nil,
                :match_type => :content_body,
                :require_product => "Drupal",
                :match_content => /(jquery\.extend\(drupal\.settings.*\\\/panopoly\\\/panopoly_admin\\\/|<link.*href=".*\/panopoly\/panopoly_admin\/)panopoly-admin-navbar.css/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Drupal Plugin"],
                :vendor => "Matt Cheney",
                :product => "Panopoly Core",
                :website => "https://www.drupal.org/project/panopoly_core",
                :match_details => "Matt Cheney Panopoly Core - panopoly-dropbutton.css Link Page Reference",
                :version => nil,
                :match_type => :content_body,
                :require_product => "Drupal",
                :match_content => /(jquery\.extend\(drupal\.settings.*\\\/panopoly\\\/panopoly_core\\\/css\\\/|<link.*href=".*\/panopoly\/panopoly_core\/css\/)panopoly-dropbutton.css/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
              {
                :type => "fingerprint",
                :category => "application",
                :tags => ["Drupal Plugin"],
                :vendor => "Matt Cheney",
                :product => "Panopoly Theme",
                :website => "https://www.drupal.org/project/panopoly_theme",
                :match_details => "Matt Cheney Panopoly Theme - panopoly-accordion.js Script Page Reference",
                :version => nil,
                :match_type => :content_body,
                :require_product => "Drupal",
                :match_content => /(jquery\.extend\(drupal\.settings.*\\\/panopoly\\\/panopoly_theme\\\/|<script.*src=".*\/panopoly\/panopoly_theme\/)panopoly-accordion.js/i,
                :hide => false,
                :paths => [{ :path => "#{url}", :follow_redirects => true }],
                :inference => false,
              },
            ]
          end
        end
      end
    end
  end
end
